---
#- name: Provision VM
#  hosts: nestedhyperv
#  gather_facts: no
#  tasks:
#    - import_tasks: tasks/prov_vm.yml

#- name: Congifure VM
#  hosts: windows
#  gather_facts: no
#  tasks:
#    - import_tasks: tasks/config_vm.yml

- name: Create AD Forest
  hosts: [firstDC]
  gather_facts: no
  tasks:
    - import_tasks: tasks/create_ad_forest.yml
