- name: Include vm env var
  include_vars:
    file: "Environments.yml"

- name: Install Active Directory
  win_feature: >
       name=AD-Domain-Services
       include_management_tools=yes
       include_sub_features=yes
       state=present

- name: Promote to DC
  microsoft.ad.domain_controller:
    dns_domain_name: "{{ forest.domain_name }}"
    domain_admin_user: "{{ forest.domain_admin_user }}"
    domain_admin_password: "{{ ansible_password }}"
    database_path: C:\Windows\NTDS
    safe_mode_password: "{{ forest.recovery_password }}"
    sysvol_path: C:\Windows\SYSVOL
    state: domain_controller

  register: ad

- name: reboot server
  win_reboot:
   msg: "Installing AD. Rebooting..."
   pre_reboot_delay: 15
  when: ad.changed

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'
