- name: Include vm env var
  include_vars:
    file: "Environments.yml"

# Set the current vm fact by matching inventory IP (ansible_host) with vm network.ip
- name: Set current vm fact
  set_fact:
    current_vm: "{{ vms | selectattr('network.ip', 'equalto', ansible_host) | list | first }}"

# change vm name
- name: Change VM name
  win_hostname:
    name: "{{ computername }}"
  register: res

- name: debug res
  debug:
    msg: "{{ res }}"

- name: Initialize a disk for current vm with d_diskpath
  community.windows.win_initialize_disk:
    disk_number: 1
  when: current_vm is defined and current_vm.d_diskpath is defined and current_vm.d_diskpath != ""

- name: Create a partition with drive letter D for current vm with d_diskpath
  community.windows.win_partition:
    drive_letter: D
    partition_size: -1
    disk_number: 1
  when: current_vm is defined and current_vm.d_diskpath is defined and current_vm.d_diskpath != ""

- name: Full format the newly created partition as NTFS and label it for current vm with d_diskpath
  community.windows.win_format:
    drive_letter: D
    file_system: NTFS
    full: True
  when: current_vm is defined and current_vm.d_diskpath is defined and current_vm.d_diskpath != ""

- name: Reboot
  win_reboot:
  when: res.reboot_required

- name: Collect facts
  setup:

#- name: Check if the Azure Connected Machine Agent is downloaded
#  win_stat:
#    path: C:\AzureConnectedMachineAgent.msi
#  register: azcmagent_win_downloaded
#
#- name: Windows サーバーに接続コンピューター エージェントをダウンロードする
#  win_get_url:
#    url: https://aka.ms/AzureConnectedMachineAgent
#    dest: C:\AzureConnectedMachineAgent.msi
#  when: (ansible_os_family == 'Windows') and (not azcmagent_win_downloaded.stat.exists)
#
#- name: Check if the Azure Connected Machine Agent is downloaded
#  win_stat:
#    path: C:\AzureConnectedMachineAgent.msi
#  register: azcmagent_win_downloaded
#
#- name: Windows サーバーに接続コンピューター エージェントをインストールする
#  win_package:
#    path: C:\AzureConnectedMachineAgent.msi
#  when: (ansible_os_family == 'Windows') and (azcmagent_win_downloaded.stat.exists)
#
#- name: 接続コンピューター エージェントが既に接続されているかどうかを確認する
#  win_command: azcmagent check
#  register: azcmagent_win_connected
#  when: ansible_os_family == 'Windows'
#  ignore_errors: yes
#  failed_when: (azcmagent_win_connected.rc not in [ 0, 16 ])
#  changed_when: False
#
#- name: Windows サーバー上の接続コンピューター エージェントを Azure Arc に接続する
#  win_shell: '& $env:ProgramFiles\AzureConnectedMachineAgent\azcmagent.exe connect --service-principal-id "{{ azure.service_principal_id }}" --service-principal-secret "{{ azure.service_principal_secret }}" --resource-group "{{ azure.resource_group }}" --tenant-id "{{ azure.tenant_id }}" --location "{{ azure.location }}" --subscription-id "{{ azure.subscription_id }}"'
#  when: (ansible_os_family == 'Windows') and (azcmagent_win_connected.rc is defined and azcmagent_win_connected.rc != 0)

- name: Reboot
  win_reboot:
  when: res.reboot_required



#- name: OpsRampエージェントインストール
#  win_package:
#    path: "\\\\nestedhyperv\\Share\\OpsRamp\\OpsRampAgent-demo001.exe"
#    Product_Id: "5DD30F80-C9BD-429B-89CA-03C0578C77B4"
#    username: administrator
#    password: NestedHypervnoP@ssw0rd



