- name: Include vm env var
  include_vars:
    file: "Environments.yml"

# change vm name
- name: Change VM name
  win_hostname:
    name: "{{ computername }}"
  register: res

- name: debug res
  debug:
    msg: "{{ res }}"

- name: Initialize a disk
  community.windows.win_initialize_disk:
    disk_number: 1
  when: 'd_diskpath'

- name: Create a partition with drive letter D
  community.windows.win_partition:
    drive_letter: D
    partition_size: -1
    disk_number: 1
  when: 'd_diskpath'

- name: Full format the newly created partition as NTFS and label it
  community.windows.win_format:
    drive_letter: D
    file_system: NTFS
    full: True
    when: 'd_diskpath'

- name: Reboot
  win_reboot:
  when: res.reboot_required

#- name: OpsRampエージェントインストール
#  win_package:
#    path: "\\\\nestedhyperv\\Share\\OpsRamp\\OpsRampAgent-demo001.exe"
#    Product_Id: "5DD30F80-C9BD-429B-89CA-03C0578C77B4"
#    username: administrator
#    password: NestedHypervnoP@ssw0rd



