- name: Include vm env var
  include_vars:
    file: "Environments.yml"

- name: Set upstream DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '{{ forest.upstream_dns_1 }}'
    - '{{ forest.upstream_dns_2 }}'

- name: Stop the time service
  win_service:
    name: w32time
    state: stopped

- name: Set NTP Servers
  win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{forest.ntp_servers}}"'

- name: Start the time service
  win_service:
    name: w32time
    state: started  

#- name: Disable firewall for Domain, Public and Private profiles
#  win_firewall:
#    state: disabled
#    profiles:
#    - Domain
#    - Private
#    - Public
#  tags: disable_firewall

- name: Install Active Directory
  win_feature: >
       name=AD-Domain-Services
       include_management_tools=yes
       include_sub_features=yes
       state=present

- name: Create Domain
  microsoft.ad.domain:
    create_dns_delegation: no
    database_path: D:\NTDS
    dns_domain_name: "{{ forest.domain_name }}"
    safe_mode_password: "{{ forest.recovery_password }}"
    sysvol_path: D:\SYSVOL
  register: ad
  ignore_errors: yes

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting due to reboot_required flag..."
    pre_reboot_delay: 15
  when: ad.reboot_required | default(false)

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'

- name: Create reverse DNS zone
  win_shell: "if($null -eq (Get-DnsServerZone -Name {{forest.reverse_dns_zone_name}})) {Add-DnsServerPrimaryZone -NetworkID {{forest.reverse_dns_zone}} -ReplicationScope Forest}"
  retries: 30
  delay: 60
  register: result           

- name: debug
  debug:
    msg: "{{ result }}"
