vms:
  - type: windows
    name: "arc-iisdemo-hrw"

    cpu: 2
    memory: 10240MB

    network:
      ip: 10.1.1.1
      netmask: 255.255.255.0
      gateway: 10.1.1.254
      dns: 192.168.1.1

    network_switch: 'Nested NAT Switch'

    src_vhd: "E:\\Hyper-V\\Virtual Hard Disks\\GoldenImages\\win2019-gold.vhdx"
    dest_vhd: "E:\\Hyper-V\\Virtual hard disks\\arc-iisdemo-hrw.vhdx"

  - type: windows
    name: "arc-iisdemo-mc"

    cpu: 2
    memory: 10240MB

    network:
      ip: 10.1.1.2
      netmask: 255.255.255.0
      gateway: 10.1.1.254
      dns: 192.168.1.1

    network_switch: 'Nested NAT Switch'

    src_vhd: "E:\\Hyper-V\\Virtual Hard Disks\\GoldenImages\\win2019-gold.vhdx"
    dest_vhd: "E:\\Hyper-V\\Virtual hard disks\\arc-iisdemo-mc.vhdx"

  - type: windows
    name: "arc-iisdemo-rc"

    cpu: 2
    memory: 10240MB

    network:
      ip: 10.1.1.3
      netmask: 255.255.255.0
      gateway: 10.1.1.254
      dns: 192.168.1.1

    network_switch: 'Nested NAT Switch'

    src_vhd: "E:\\Hyper-V\\Virtual Hard Disks\\GoldenImages\\win2019-gold.vhdx"
    dest_vhd: "E:\\Hyper-V\\Virtual hard disks\\arc-iisdemo-rc.vhdx"
    
  - type: windows
    name: "arc-iisdemo-ssh"

    cpu: 2
    memory: 10240MB

    network:
      ip: 10.1.1.4
      netmask: 255.255.255.0
      gateway: 10.1.1.254
      dns: 192.168.1.1

    network_switch: 'Nested NAT Switch'

    src_vhd: "E:\\Hyper-V\\Virtual Hard Disks\\GoldenImages\\win2019-gold.vhdx"
    dest_vhd: "E:\\Hyper-V\\Virtual hard disks\\arc-iisdemo-ssh.vhdx"

  - type: windows
    name: "arc-iisdemo-wac"

    cpu: 2
    memory: 10240MB

    network:
      ip: 10.1.1.5
      netmask: 255.255.255.0
      gateway: 10.1.1.254
      dns: 192.168.1.1

    network_switch: 'Nested NAT Switch'

    src_vhd: "E:\\Hyper-V\\Virtual Hard Disks\\GoldenImages\\win2019-gold.vhdx"
    dest_vhd: "E:\\Hyper-V\\Virtual hard disks\\arc-iisdemo-wac.vhdx"
